# Generated by Django 4.2.7 on 2023-11-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('admin_permissions', 'Can manage users, system configurations, and overall system settings'), ('biller_permissions', 'Can create bills, monitor payments, and manage biller-specific settings'), ('customer_permissions', 'Can view and pay bills, receive reminders, and access payment history')],
            },
        ),
    ]
