# Generated by Django 5.0 on 2023-12-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_user_type_biller_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiftConnection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=255)),
                ('companyAddress', models.CharField(max_length=255)),
                ('contactPhone', models.CharField(max_length=255)),
                ('contactEmail', models.CharField(max_length=255)),
            ],
        ),
    ]
